services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - uv-cache:/root/.cache/uv
    env_file:
      - ./api/.env
    depends_on:
      - db

  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - api

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongod.conf:/tmp/mongod.conf:ro
      - ./mongodb/logs:/var/log/mongodb
    command: ["mongod", "--config", "/tmp/mongod.conf"]


volumes:
  uv-cache:
  mongodb_data:
