[project]
name = "sus-food-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "motor>=3.7.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]